---
apiVersion: v1
kind: Service
metadata:
  name: ambassador
  labels:
    service: ambassador
spec:
  selector:
    service: ambassador
  type: LoadBalancer
  ports:
  - name: ambassador
    port: 80
    targetPort: 80