#Instruction for k8s service for first micro-service

---
apiVersion: v1
kind: Service
metadata:
  name: service-first
  labels:
    app: service-first
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  gateway.registry.service.first
      prefix: /prgx/service/first/
      service: service-first:8020
      timeout_ms: 10000
spec:
  selector:
    app: pod.micro.first
  type: ClusterIP
  ports:
    - name: http
      port: 8020
      protocol: TCP
---